# Generated by Django 4.1.3 on 2022-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pet",
        ),
        migrations.AddField(
            model_name="group",
            name="update_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
